#!/bin/bash

make distclean && make mini6410_nand_config && make && /bin/cp -f u-boot.bin u-boot-nand.bin || exit 1
#make distclean && make mini6410_sd_config   && make && /bin/cp -f u-boot.bin u-boot-sd.bin   || exit 1

